<?php

namespace AppBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllArticles(){
        $qb = $this->createQueryBuilder('a');
        $qb->SELECT('a');
        return $qb->getQuery()->getArrayResults();
    }



}
