<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMessages($id){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.receveur = :id');
        $qb->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
